from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, AsyncIterator

from cascade import ProviderError, ProviderRateLimitedError, ProviderUnavailableError

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class AIServiceConfig:
    name: str
    model: str
    key: str
    url: str | None


class AIServiceError(ProviderError):
    """Readable error to show on the frontend, without crashing the server."""
    message = "AI service error."


class AIServiceProviderUnavailableError(ProviderUnavailableError, AIServiceError):
    """Transient upstream overload (HTTP 503) — worth retrying."""
    message = "AI service unavailable after every retry."


class AIServiceProviderRateLimitedError(ProviderRateLimitedError, AIServiceError):
    """The upstream model API rejected the request for rate limiting (HTTP 429)."""
    message = "The AI service rate limit was exceeded."


def content_to_text(content: Any, provider_name: str = "LLM") -> str:
    """Flattens provider-neutral attachment blocks to plain text.
    Binary (base64) attachments are skipped if unsupported.
    """
    if isinstance(content, str):
        return content
    parts: list[str] = []
    for block in content:
        source = block["source"]
        if source["type"] == "text":
            parts.append(f"[Attachment: {block['filename']}]\n{source['data']}")
        else:
            logger.warning(
                "Skipping unsupported binary attachment '%s' for %s.",
                block["filename"],
                provider_name,
            )
    return "\n\n".join(parts)


class LLMProvider(ABC):
    @abstractmethod
    def __init__(self, config: AIServiceConfig) -> None:
        raise NotImplementedError

    @abstractmethod
    def generate(self, system_prompt: str, history: list[dict]) -> str:
        """Returns the complete reply text for `history` (list of {role, content}).
        Raises AIServiceError on failure, never an unhandled exception."""
        raise NotImplementedError

    @abstractmethod
    async def generate_stream(
        self, system_prompt: str, history: list[dict]
    ) -> AsyncIterator[str]:
        """Yields response text chunks incrementally as they are generated by the model.
        Raises AIServiceError on failure, never an unhandled exception."""
        raise NotImplementedError
        yield ""  # Satisfies type generators