from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, AsyncIterator, Callable

from cascade import OnRetry, ProviderError, ProviderRateLimitedError, ProviderUnavailableError

logger = logging.getLogger(__name__)

MetadataCallback = Callable[[str, Any], None]

@dataclass(frozen=True)
class AIServiceConfig:
    driver: str
    model: str
    key: str
    url: str | None
    # Optional: falls back to `driver` (see AppConfig._parse_ai_services).
    ui_label: str
    ui_description: str | None = None


class AIServiceError(ProviderError):
    """Readable error to show on the frontend, without crashing the server."""
    message = "AI service error."


class AIServiceProviderUnavailableError(ProviderUnavailableError, AIServiceError):
    """Transient upstream overload (HTTP 503) — worth retrying."""
    message = "AI service unavailable after every retry."


class AIServiceProviderRateLimitedError(ProviderRateLimitedError, AIServiceError):
    """The upstream model API rejected the request for rate limiting (HTTP 429)."""
    message = "The AI service rate limit was exceeded."


def content_to_text(content: Any, provider_name: str = "LLM") -> str:
    """Flattens provider-neutral attachment blocks to plain text.
    Binary (base64) attachments are skipped if unsupported.
    """
    if isinstance(content, str):
        return content
    parts: list[str] = []
    for block in content:
        source = block["source"]
        if source["type"] == "text":
            parts.append(f"[Attachment: {block['filename']}]\n{source['data']}")
        else:
            logger.warning(
                "Skipping unsupported binary attachment '%s' for %s.",
                block["filename"],
                provider_name,
            )
    return "\n\n".join(parts)


class LLMProvider(ABC):
    """Constructors are deliberately not part of this contract: a leaf
    implementation (see AnthropicProvider et al.) is built from one
    AIServiceConfig, while CascadingLLMProvider (ai/cascading_llm_provider.py)
    is built from an ordered list of LLMProviders — polymorphic dispatch
    only ever happens through generate()/generate_stream() below, never
    through __init__, so forcing one constructor shape on every
    implementation would only get in the way."""

    @abstractmethod
    def generate(
        self, system_prompt: str, history: list[dict], on_retry: OnRetry | None = None
    ) -> str:
        """Returns the complete reply text for `history` (list of {role, content}).
        Raises AIServiceError on failure, never an unhandled exception.
        `on_retry` is awaited before each backoff sleep — only ever called
        by a provider that itself retries (see CascadingLLMProvider); a
        leaf provider accepts it purely so callers can treat any
        LLMProvider uniformly, and simply never calls it."""
        raise NotImplementedError

    @abstractmethod
    async def generate_stream(
        self, system_prompt: str, history: list[dict], on_retry: OnRetry | None = None, on_metadata: MetadataCallback | None = None
    ) -> AsyncIterator[str]:
        """Yields response text chunks incrementally as they are generated by the model.
        Raises AIServiceError on failure, never an unhandled exception.
        See generate() above for `on_retry`."""
        raise NotImplementedError
        yield ""  # Satisfies type generators