database: 
  url: sqlite:///avance.db

chat-service:
  transport: websocket

ai-service:
  - name: gemini
    model: gemini-flash-lite-latest
    key: <your-key>
  - name: gemini
    model: gemini-3.1-flash-lite
    key: <your-key>
  - name: gemini
    model: gemini-3.5-flash-lite
    key: <your-key>

model-service:
  file-watch-enabled: true
  
